name: CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main   # Runs when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t arnabvais/my-node-app:latest .

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          docker push arnabvais/my-node-app:latest
          # 5. Deploy to remote server via SSH
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull arnabvais/my-node-app:latest
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d -p 5000:3000 --name my-node-app arnabvais/my-node-app:latest
  